/**
 * generated by Xtext
 */
package org.softlang.megal.language.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.softlang.megal.Entity;
import org.softlang.megal.EntityType;
import org.softlang.megal.Named;
import org.softlang.megal.Relationship;
import org.softlang.megal.RelationshipType;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class MegalLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public MegalLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Named it) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = it.getName();
    _builder.append(_name, "");
    return _builder.toString();
  }
  
  public String text(final Relationship it) {
    StringConcatenation _builder = new StringConcatenation();
    Entity _left = it.getLeft();
    String _name = _left.getName();
    _builder.append(_name, "");
    _builder.append(" ");
    RelationshipType _type = it.getType();
    String _name_1 = _type.getName();
    _builder.append(_name_1, "");
    _builder.append(" ");
    Entity _right = it.getRight();
    String _name_2 = _right.getName();
    _builder.append(_name_2, "");
    return _builder.toString();
  }
  
  public String image(final Entity object) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("entity.gif");
    return _builder.toString();
  }
  
  public String image(final EntityType object) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("entity_type.gif");
    return _builder.toString();
  }
  
  public String image(final Relationship object) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("relationship.gif");
    return _builder.toString();
  }
  
  public String image(final RelationshipType object) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("relationship_type.gif");
    return _builder.toString();
  }
}
