/**
 * generated by Xtext
 */
package org.softlang.megal.language.serializer;

import org.softlang.megal.language.serializer.AbstractMegalSyntacticSequencer;

@SuppressWarnings("all")
public class MegalSyntacticSequencer extends AbstractMegalSyntacticSequencer {
}
