/**
 * generated by Xtext
 */
package org.softlang.megal.language.serializer;

import org.softlang.megal.language.serializer.AbstractMegalSemanticSequencer;

@SuppressWarnings("all")
public class MegalSemanticSequencer extends AbstractMegalSemanticSequencer {
}
