/*
* generated by Xtext
*/
package org.softlang.megal.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MegalUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.softlang.megal.language.ui.internal.MegalActivator.getInstance().getInjector("org.softlang.megal.language.Megal");
	}
	
}
